### PR TITLE
PEP8 formatting + etc

### PR DESCRIPTION
**Pull request by lespea**
One thing led to another and this got to be quite a big change... probably easiest to go through each commit individually vs everything all at once.  This is on top of my other pull requests so probably do this last if at all... If some of these changes don't sit right with you let me know which one(s) and I'll roll them back, but this should mostly all be pep8 compliant changes with a few refactorings that seemed like they'd fit.

Tested this against a few MFTs I had laying around and didn't notice any changes in the output (ran diff).

### CODE REVIEW

**Comment by dkovar** [comment]
Greetings,
I applied the earlier patches and this one is now in conflict. Could you resolve the conflicts and also update the Readme with your changes and how you'd like to be identified? I'll then accept this, update the version numbers, test it, push it, ....

Thanks very much.

-David

**Comment by lespea** [comment]
Okay should be good to go.  I think I forgot to send a different pull request earlier which is why it didn't properly merge.  Whoops.

Oh forgot to update the readme 1 sec

**Comment by lespea** [comment]
Okay now I think it's ready.  I didn't update the readme-changelog as it looks like it's fallen out of sync and not sure what you're doing with it.

And np this is a great library, thanks for creating it!

-Adam-

**Comment by dkovar** [comment]
Greetings,

Ah, yea, README is out of date because V2 is tracked in CHANGES.txt. I noted that in README.txt.

Good to go!

-David

**Pull request merged**
